name: Java CI

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.4.1
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn clean package
